global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

k8gb:
  imageRepo: absaoss/k8gb # image tag is defined in Chart.AppVersion, see Chart.yaml
  ingressNamespace: "k8gb"
  dnsZone: "cloud.example.com" # dnsZone controlled by gslb
  edgeDNSZone: "example.com" # main zone which would contain gslb zone to delegate
  edgeDNSServer: "1.1.1.1" # use this DNS server as a main resolver to enable cross k8gb DNS based communication
  clusterGeoTag: "eu" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us" # comma-separated list of external gslb geo tags to pair with
  hostAlias: # use https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ inside operator pod. Useful for advanced testing scenarios and to break dependency on EdgeDNS for cross k8gb collaboration
    enabled: false
    ip: "172.17.0.1"
    hostnames:
     - "gslb-ns-cloud-example-com-us.example.com"
  reconcileRequeueSeconds: 30
  exposeCoreDNS: false # Create Service type LoadBalancer to expose CoreDNS

externaldns:
  image: k8s.gcr.io/external-dns/external-dns:v0.7.6
  interval: "20s"
  expose53onWorkers: true # open 53/udp on workers nodes with nginx controller

coredns:
  isClusterService: false
  image:
    repository: absaoss/k8s_crd
    tag: "v0.0.1"
  serviceAccount:
    create: true
    name: coredns
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: cache
      parameters: 30
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    - name: loadbalance
      parameters: round_robin
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: k8s_crd
      parameters: .
      configBlock: |-
        resources DNSEndpoint
        filter k8gb.absa.oss/dnstype=local

infoblox:
  enabled: false
  gridHost: 10.0.0.1
  wapiVersion: 2.3.1
  wapiPort: 443
  sslVerify: true
  httpRequestTimeout: 20
  httpPoolConnections: 10

route53:
  enabled: false
  hostedZoneID: ZXXXSSS
  irsaRole: arn:aws:iam::111111:role/external-dns

ns1:
  enabled: false
